title: "Poverty Rates by Country (1995-2023): Global Longitudinal Da"
description: "Comprehensive longitudinal dataset (1995-2023) on poverty rates across 30 countries in Sub-Saharan Africa, South Asia, East Asia, Latin America, MENA,"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/poverty-rates-by-country-1995-2023-global-longitudinal-dataset"
